---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v0/posts/{post_id}/comments":
    post:
      summary: Creates a comment
      tags:
      - Comment
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Comment created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/v0/users/{user_id}/posts":
    get:
      summary: Get the posts from a given user
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Post found
          content:
            application/json:
              schema:
                type: array
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                required:
                - id
                - title
                - text
        '404':
          description: User not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
